collections:
  methods:
    output: true
    permalink: /stories/:path/
    order:
      - northwest.md
      - northeast.md
      - southwest.md
      - southeast.md
      - central.md
      - restaurant.md
      - hawker.md
      - home-based-business.md
      - halal.md
      - vegetarian.md
      - international.md
      - bakery.md
defaults:
  - scope:
      path: ""
      type: "methods"
    values:
      layout: "method"

plugins:
  - jekyll-seo-tag

include: [_redirects]
